### PR TITLE
Adding Unit Driven tests using Google Test frameworks

### LINKED ISSUE #15: Convert and extend existing tests in unit tests
## Motivation
Some tests are already implemented, but they are not part of a test framework.
Reimplementing and extending them with ctest or google test is crucial for CI and CD.

## Modification
Add units tests written with ctest or Google Test for Rucio-FUSE

### PR DESCRIPTION
**Pull request by viveknigam3003**
This PR handles the unit driven tests for the FUSE Module using Google Tests.
This closes #15 .

### CODE REVIEW

**Comment by gabrielefronze** [comment]
Ciao @viveknigam3003 !
It's been a long time. This PR has some conflicts, can you have a look? Just in case you cannot let me know!

**Comment by viveknigam3003** [comment]
Hey @gabrielefronze, I'll try to resolve the merge conflicts by the end of this week and then we can maybe merge it. Although I have lost touch with C++ for about the past 10 months yet I'll try to give it an honest shot. 😅 
I'll get in touch with you regarding the same if I face any issues.

Thanks for notifying me about this. I guess you're cleaning up all the pending PRs in this repo.

**Comment by mlassnig** [comment]
@viveknigam3003 @gabrielefronze ping. what should I do with this? :-)

**Comment by mlassnig** [comment]
Closing due to inactivity

**Pull request closed without merging**
