### PR TITLE
Adding a trivial dockerfile for easy portable testing

### PR DESCRIPTION
**Pull request by astroclark**
Just a simple dockerfile to help with testing

### CODE REVIEW

**Comment by gabrielefronze** [comment]
That's a good addition, much needed for CI.
To keep things *really* portable I'd make the Dockerfile independent from the fact it is placed inside this particular repo, but, instead, I'd make it install this package by cloning the repository itself.

**Review by gabrielefronze — CHANGES_REQUESTED** [review]
I'd change here lines 30-38 to something in the lines of:
```
WORKDIR /opt
RUN git clone https://github.com/rucio/fuse-posix.git
```

**Comment by astroclark** [comment]
In general, I completely agree (and indeed was cloning at first) but wanted to be able to edit the server configuration before building the container.  I can just add a COPY after the clone in the version i'm using, i guess.

**Comment by gabrielefronze** [comment]
Since the json runtime parsing will come at a given point, the best option would be bind mounting the `globals.cpp` file from the host after having cloned the repo (overwriting the original copy).

When the json parsing will be implemented, the same mechanism may be used to pass through the json config file!

**Comment by astroclark** [comment]
Yep, I tried that but it behaved as if it was using the default.  I'll check again.

**Comment by astroclark** [comment]
Confirmed:  bind the file:
```
docker run -it -v $HOME/Desktop/globals.cpp:/opt/fuse-posix/source/globals.cpp --device /dev/fuse --cap-add SYS_ADMIN jclarkastro/fuse-posix
```
Then try to access the `/ruciofs`:
```
----------------------------------------
Activating rucio fuse-posix interface...
Creating CURL instance
curl_easy_perform() failed: Couldn't resolve host name
curl_easy_perform() failed: Couldn't resolve host name
```
And the file is definitely bound correctly:
```
[root@c37913ff9076 opt]# head fuse-posix/source/globals.cpp 
//
// Created by Gabriele Gaetano Fronzé on 2019-10-17.
//

#include <globals.h>

std::unordered_map<std::string, rucio_server> rucio_server_map = {
                                                                  {
                                                                    "rucio-server",
                                                                    rucio_server("https://ligo-rucio.nautilus.optiputer.net",
```

But when i *build* with the `globals.cpp`:
```
# ls /ruciofs/rucio-server
ls: cannot access ER8: Software caused connection abort
ls: cannot access O3: Transport endpoint is not connected
ls: cannot access O2: Transport endpoint is not connected
ls: reading directory .: Transport endpoint is not connected
ER8  O2  O3
```

**Comment by gabrielefronze** [comment]
I definitely have to add the runtime parsing of the settings.
Let's wait for that feature.
Please rebase on master: I got to merge several commits and force push.

**Comment by astroclark** [comment]
That was a horrible mess, i guess because of the forced push upstream?

**Comment by gabrielefronze** [comment]
I think so.
I think you container is not really a part of this project, but more of a submodule.
What about hosting it on your repo and adding it to this repo as a submodule?
Does it make sense to you?

**Comment by gabrielefronze** [comment]
@astroclark I managed to implement runtime parsing of the `settings.json` file.
Please align this PR to this new paradigm, bind mounting the configuration file from the container host! :)

**Review by gabrielefronze — APPROVED** [review]

**Review by gabrielefronze — COMMENTED** [review]
Add bind mounting of external `settings.json` file, since the compile-time parameters in `globals.cpp` are now deprecated.

**Comment by gabrielefronze** [comment]
@astroclark the addition of a container here is superseded by the addition of ruciofs to the containers repo, soon becoming a PR https://github.com/gabrielefronze/containers

**Pull request closed without merging**
